export const ESTADOS_SOLICITUD = [
  'CREADA',
  'REGISTRADA',
  'EN_VENTANILLA',
  'DEVUELTA_VENTANILLA',
  'VALIDADA',
  'EN_REVISION_UPC',
  'EN_ENCARGADO_UPC',
  'EN_UPC',
  'DEVUELTA_UPC',
  'EN_DIRECCION',
  'DEVUELTA_DIRECCION',
  'EN_DNCD',
  'DEVUELTA_DNCD',
  'PENDIENTE_PAGO',
  'PAGO_CONFIRMADO',
  'APROBADA',
  'RECHAZADA',
  'DENEGADA',
  'RESOLUCION_EMITIDA',
  'CERTIFICADO_EMITIDO',
  'COMPLETADA'
];

export const ESTADOS_CATALOGO_DEFINICION = [
  { nombre: 'CREADA', descripcion: 'Solicitud recién creada', inicial: true, final: false, orden: 1 },
  { nombre: 'REGISTRADA', descripcion: 'Registrada por ventanilla', inicial: false, final: false, orden: 2 },
  { nombre: 'EN_VENTANILLA', descripcion: 'En revisión por Ventanilla Única', inicial: false, final: false, orden: 3 },
  { nombre: 'DEVUELTA_VENTANILLA', descripcion: 'Devuelta por Ventanilla para completar documentos', inicial: false, final: false, orden: 4 },
  { nombre: 'VALIDADA', descripcion: 'Validada en ventanilla', inicial: false, final: false, orden: 5 },
  { nombre: 'EN_REVISION_UPC', descripcion: 'En revisión técnica de UPC', inicial: false, final: false, orden: 6 },
  { nombre: 'EN_ENCARGADO_UPC', descripcion: 'Revisión final por encargado UPC', inicial: false, final: false, orden: 7 },
  { nombre: 'EN_UPC', descripcion: 'En evaluación técnica UPC', inicial: false, final: false, orden: 8 },
  { nombre: 'DEVUELTA_UPC', descripcion: 'Devuelta por UPC para aclaraciones', inicial: false, final: false, orden: 9 },
  { nombre: 'EN_DIRECCION', descripcion: 'En aprobación de Dirección', inicial: false, final: false, orden: 10 },
  { nombre: 'DEVUELTA_DIRECCION', descripcion: 'Devuelta por Dirección', inicial: false, final: false, orden: 11 },
  { nombre: 'EN_DNCD', descripcion: 'En revisión final DNCD', inicial: false, final: false, orden: 12 },
  { nombre: 'DEVUELTA_DNCD', descripcion: 'Devuelta por DNCD', inicial: false, final: false, orden: 13 },
  { nombre: 'PENDIENTE_PAGO', descripcion: 'Pendiente confirmación de pago', inicial: false, final: false, orden: 14 },
  { nombre: 'PAGO_CONFIRMADO', descripcion: 'Pago confirmado', inicial: false, final: false, orden: 15 },
  { nombre: 'APROBADA', descripcion: 'Solicitud aprobada', inicial: false, final: true, orden: 16 },
  { nombre: 'RECHAZADA', descripcion: 'Solicitud rechazada', inicial: false, final: true, orden: 17 },
  { nombre: 'DENEGADA', descripcion: 'Solicitud denegada', inicial: false, final: true, orden: 18 },
  { nombre: 'RESOLUCION_EMITIDA', descripcion: 'Resolución emitida', inicial: false, final: true, orden: 19 },
  { nombre: 'CERTIFICADO_EMITIDO', descripcion: 'Certificado emitido', inicial: false, final: true, orden: 20 },
  { nombre: 'COMPLETADA', descripcion: 'Trámite completado', inicial: false, final: true, orden: 21 }
];
